{ lib, ... }:
{
  options.editors.files = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options.text = lib.mkOption {
          type = lib.types.lines;
          description = "File contents.";
        };
      }
    );
    default = { };
    example = {
      ".nvim.lua".text = "vim.lsp.enable('zls')";
    };
    description = ''
      Files generated by the enabled editor modules, keyed by path relative to
      the project root. Integrations write these into the project.
    '';
  };
}
